tasks:
  MTV:
    rss:
    series:
      settings:
        group 1:
          qualities:
            - 720p hdtv
          propers: 1 days
      group 1:
        - 2.Broke.Girls
        - 24.Legacy
        - American.Horror.Story
        - Arrow
        - Billions
        - Black.Mirror
        - Black.Sails
        - Blindspot
        - Crazy.Ex-Girlfriend
        - Criminal.Minds
        - Colony
        - DCs.Legends.of.Tomorrow
        - Elementary
        - Fear.The.Walking.Dead
        - Frequency
        - Grimm
        - Gotham
        - Greys.Anatomy
        - Hawaii.Five-0
        - High.Maintenance
        - Homeland
        - How.to.Get.Away.with.Murder
        - iZombie
        - Jane.the.Virgin
        - Lethal.Weapon
        - Legion
        - Lucifer
        - Marvels.Agents.of.S.H.I.E.L.D
        - Madam.Secretary
        - Masters.of.Sex
        - Modern.Family
        - Mom
        - Mr.Robot
        - New.Girl
        - Orphan.Black
        - Quantico
        - Scorpion
        - Shameless.US
        - South.Park
        - Supernatural
        - Suits
        - Supergirl
        - Scandal.US
        - Teen.Wolf
        - The.100
        - The.Blacklist
        - The.Expanse
        - The.Exorcist
        - The.Flash
        - The.Last.Man.on.Earth
        - The.Magicians
        - The.Originals
        - The.Strain
        - The.Vampire.Diaries
        - The.Walking.Dead
        - This.Is.Us
        - Vikings
        - Westworld
        - Z.Nation
        - Timeless
      normal:
        - The.Big.Bang.Theory:
            qualities:
              - 720p hdtv
              - 1080p hdtv
    download:
    verify_ssl_certificates: no